Feature/week1 hyunkuk
mash-up-kr/Android_12nd_mvvm pull request #2
Opened 2022-04-25 16:04 UTC by 014967

2022-04-27 10:14 UTC, jaeryo2357 reviewed
첫 PR이라 부담되셨을 텐데 수고많으셨습니다!
코드가 너무 깔끔해서 읽기도 편하고 좋았어요!

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +            }
이 부분은 의도하신 부분과 다를 수 있어서 참고만 해주세요!
TextView.setText()에는 null 값이 들어갈 수도 있어서 null-check을 안해주기도 하더라구요
```suggestion
            if (repo.language != null) {
                binding.tvMainLanguage.text = repo.language
            }
```

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +    RecyclerView.Adapter<RepoAdapter.ViewHolder>(),
시간 되실 때 ListAdapter도 적용해보시면 좋을 것 같아요!

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/network/ApiClient.kt
> +    }
singleton을 고려하셨다면 `object`로 선언해도 좋아보여요!
추가로 by lazy로 객체를 초기화하면 멀티쓰레드 환경에서 가장 쉬운 singleton 구현 방식이라고 하더라구요.

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/network/ApiClient.kt
> +            .build()
okhttp logging에 대해서 혹시 알고 있으신가요?

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/util/RetrofitExt.kt
> +package com.example.myapplication.util
확장함수 선언 👍  짱이네요!
저는 보통 확장함수는 `extensions` pacakgae에 모아두고 있어요. 참고만 해주세요!

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/view/search/SearchFragment.kt
> +    }
외부에서 호출하는 함수가 아니라서 저는 context를 넣어줄 필요는 없을 것 같아요!
```suggestion
    private fun initUI() {
        repoAdapter = RepoAdapter()
        binding.rvSearch.layoutManager = LinearLayoutManager(requireContext())
        binding.rvSearch.adapter = repoAdapter

        searchPresenter.setRepoAdapterModel(repoAdapter)
        searchPresenter.setRepoAdapterView(repoAdapter)

        searchPresenter.getRepoList()
    }
```

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/ab_main"
```suggestion
        app:layout_constraintTop_toBottomOf="@id/ab_main"
```

약간 컨벤션 느낌이지만 id를 추가 선언할때만 +사용하면 좋을 것 같습니다!

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/res/layout/fragment_search.xml
> +
헉 Lottie까지.. 대박 👍

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/res/layout/fragment_search.xml
> +            tools:listitem="@layout/item_search"
코드 상에서 layoutmanager 객체를 만들어서 속성을 부여하지 않느다면 xml에서 지정해줘도 좋을 것 같아요!
```suggestion
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_search"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
            tools:itemCount="20"
            tools:listitem="@layout/item_search"
```

2022-04-27 10:14 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/presenter/search/SearchAdapterContract.kt
> +}
mvp 구조는 adpater에도 적용되는군요.. 알아갑니다

2022-04-27 12:23 UTC, Sookhee commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +    }
크게 상관은 없지만 데이터를 세팅할 때 setData()와 notifyAdapter()를 항상 같이 불러줄 예정이라면 두개를 하나의 함수로 처리하면 어떨까요?

```suggestion
    override fun setData(repos: List<Repository>) {
        this.repos = repos
        notifyDataSetChanged()
    } 
```

2022-04-27 12:23 UTC, Sookhee commented on 김현국/app/src/main/java/com/example/myapplication/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(
와 Base클래스까지 만들어주신거 너무 대박이에요..! 👍

2022-04-27 12:23 UTC, Sookhee commented on 김현국/app/src/main/java/com/example/myapplication/network/ApiInterface.kt
> +        @Query("q") q: String?
이 함수 사용하는 부분에서는 q를 String으로 받아서 넘겨주던데 혹시 여기서 nullable로 선언한 이유가 있나요?
그리고 프로젝트 빌드가 잘 안돼서 돌려보진못했는데ㅠㅠ retrofit 통신할 때 만약 쿼리값으로 null이 들어가면 어떻게 되는지 궁금해요..!

2022-04-27 12:26 UTC, Sookhee commented
우왕 1주차 과제 수고하셨습니다~
커밋 나눠주셔서 보기 너무 편했고, 또 코드 보면서 많이 배웠어요 감사합니다! ㅎㅎ

2022-04-27 13:39 UTC, 014967 commented on 김현국/app/src/main/res/layout/fragment_search.xml
> +            tools:listitem="@layout/item_search"
와?! 이런 방법이 있는지는 몰랐어요 알아갑니다!!!!

2022-04-27 14:14 UTC, 014967 commented on 김현국/app/src/main/java/com/example/myapplication/network/ApiClient.kt
> +    }
그거를 미처 생각을 못했어요 ㅠㅠ.. !!

2022-04-27 14:38 UTC, 014967 commented on 김현국/app/src/main/java/com/example/myapplication/network/ApiClient.kt
> +            .build()
몰랐어요 찾아봤더니 좋은 거 같아요 사용해볼께요!!

2022-04-28 05:39 UTC, 014967 commented on 김현국/app/build.gradle
> +}
version.properties 파일을 만들어서 관리를 해봐야겠어요!

2022-04-28 05:40 UTC, 014967 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +    private var repos: List<Repository>? = emptyList()
네네 맞아요 수정했습니당

2022-04-28 05:40 UTC, 014967 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +    class ViewHolder(private val binding: ItemSearchBinding) :
네네 수정했습니당

2022-04-28 11:36 UTC, seunghee63 reviewed
저도 이번 과제를 하면서 MVP 구조를 처음 적용해 보았는데 아직 작업중이라 🥲  구조적인 면에서 피드백을 드리지 못했네요 ㅜㅜ 제 과제가 완성되면 구조적인 부분을 중점으로해서 한번 더 리뷰 남겨보도록 하겠습니당 !
일찍 올려주셨는데 리뷰가 늦어서 죄송합니다. 수고하셨어요 ~

2022-04-28 11:36 UTC, seunghee63 commented on 김현국/app/src/main/res/layout/fragment_detail.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
마이너해서 리뷰하기 다소 민망하지만.. 
xml 파일들이 조금 규칙적이지 않은 부분들이 있는것 같아요!! (공백 라인 수 같은..)
그래도 추후에 협업할것을 대비해서 조금 신경써서 작성하거나 lint 같은걸 걸어줘서 한번 체크하고 올려도 좋을 것 같네요 ㅎㅎ

2022-04-28 11:36 UTC, seunghee63 commented on 김현국/app/src/main/java/com/example/myapplication/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(
개인적인 의견이지만, 프로젝트에서 사용성이 떨어지는 베이스는 구현하지 않는것이 맞다고 생각합니당. 가령 SingleActivity 구조인데 BaseActivity를 구현하는 것 같은.. 
그런데 저도 가끔 과제같은걸 하다보면 전에 구현해 뒀던 것을 활용하고자 혹은 제가 아는것을 보여주고자(😅) 활용도가 높지 않은 Base를 구현하기도 합니다ㅎㅎ.. 
과제를 보시는 입장에서 혹은 다른분들은 어떻게 생각하시는지 궁금해서 코드리뷰는 아니지만 의견 남겨봅니닷

2022-04-28 11:36 UTC, seunghee63 commented on 김현국/app/src/main/java/com/example/myapplication/model/RepoListModel.kt
> +                val repoList: List<Repository> = response.body()!!
`!!`를 사용하지 않는 방법을 고민해 보시면 좋을것 같아요 ! (예외처리 라던지..?!)

2022-04-28 11:36 UTC, seunghee63 commented on 김현국/app/src/main/java/com/example/myapplication/base/BaseActivity.kt
> +    val binding get() = _binding!!
@jaeryo2357
Fragment 는 binding 객체가 여러번 생성되고
Activity 에서는 binding 객체가 여러번 생성되지 않는다는 것이 무엇인지 조금 더 설명해주실수 있으신가용 🥲

2022-04-29 06:39 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +            }
아이구 suggestion을 수정안하고 코멘트를 달아서 다시 수정했습니다~ ㅋㅋㅋㅋ

2022-04-29 06:46 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +    class ViewHolder(private val binding: ItemSearchBinding) :
@seunghee63  아하 제가 말씀드린 확장성이 애매하게 전달될 수 있겠네요!
제가 말한 확장성이란 프로젝트 전체적인 관점으로 다양한 화면이 생길 수 있고, 다양한 ViewHolder들이 생길 수 있어서
이름을 ViewHolder 보다는 기능, UI에 맞는 이름으로 변경하면 좋겠다는 뜻이었습니다!!

2022-04-29 06:50 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/base/BaseActivity.kt
> +    val binding get() = _binding!!
아하 넵!! @seunghee63 
Fragment는 내부적으로 Activity와 다르게 Lifecycle이 2개가 존재합니다.

Activity는 라이프 사이클 시작인 `onCreate`에서 뷰를 생성하기 때문에 Lifecycle == View가 되지만

Fragment는 onCreate와 onCreateView로 나뉘어, 즉 Fragment의 Lifecycle != View가 됩니다.
Fragment Lifecycle 특성 상 화면 전환 등으로 인해 뷰가 생성되고 죽는 과정이 여러번 발생할 수 있어서
Fragment Lifecycle과 Fragment View Lifecycle을 별개로 봐야 한다고 알고있습니다!

2022-04-29 06:54 UTC, jaeryo2357 requested changes
리팩토링 하신 것에 대해서 추가 코드리뷰 드립니다!!!

2022-04-29 06:54 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +    lateinit var onItemClick: OnItemClick
itemClick 리스너를 무조건 등록한다는 조건이라면 `lateinit var`보다는 생성자에서 주입받게 해도 될 것 같아요!
```suggestion
class RepoAdapter(
     private val onItemClick: OnItemClick
    ) :
    ListAdapter<Repository, RepoAdapter.RepoViewHolder>(diffUtil),
    SearchAdapterContract.View,
    SearchAdapterContract.Model {
```

2022-04-29 06:54 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +        val diffUtil = object : DiffUtil.ItemCallback<Repository>() {
외부에서 diffUtil을 접근하지 않는다면 `private`로 선언해도 될 것 같습니다!

2022-04-29 19:23 UTC, jaeryo2357 commented on 김현국/app/src/main/java/com/example/myapplication/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(
오 저는 이런 관점은 생각해보지 못한 것 같네요
저는 개인적으로는 프로젝트를 구현할 때 확장성을 고려해서 생각하는 편이라 프로젝트를 시작할때 base 코드들 부터 만들었던 것 같네요. 말씀해주신 SingleActivity 구조라고 할 때 BaseActivity를 구현한다는 것은 약간 고민해볼 주제인 것 같긴합니다! 팀원과 의논을 하여 정말 추후 여러 기능이 추가되어도 반드시 하나의 Activity만 존재한다는 것을 보장할 수 있다면 안만들어도 될 것 같아요.

그런데 현재 코드처럼 BaseFragment는 base로 정의하기 좋아보여요!
Fragment ViewLifecycle에 맞는 ViewBinding 객체 관리부터 progress 띄우는 로직이나 toast 또는 snackbar 관리하는 기능을 담아두면 좋을 것 같네요

2022-05-01 03:30 UTC, jaeryo2357 approved these changes
수고많으셨습니다!! 짱짱

2022-05-01 05:27 UTC, 014967 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +    }
네네 좋은 방안이예요 반영했습니다!

2022-05-01 05:28 UTC, 014967 commented on 김현국/app/src/main/res/layout/fragment_detail.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
네네 확인했습니다

2022-05-01 05:32 UTC, 014967 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +        val diffUtil = object : DiffUtil.ItemCallback<Repository>() {
반영했습니다~!

2022-05-01 05:53 UTC, 014967 commented on 김현국/app/src/main/java/com/example/myapplication/adapter/RepoAdapter.kt
> +    lateinit var onItemClick: OnItemClick
이거는 마땅한 방법을 못찾아서 mvvm 구조에서 변경해볼께용

2022-05-01 05:55 UTC, 014967 commented on 김현국/app/src/main/java/com/example/myapplication/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(
액티비티의 사용빈도에 따라서 고민해서 작성해야겠네요!!

2022-05-01 06:00 UTC, merged